/* English. Kennel-club terms follow FCI usage: the breeding
   qualifications (ACE, ACES, ACU, ACUS, ACSS), Annex A and the
   variety names stay in their original form throughout the FCI. */
TEXTOS.en = {
  "La plataforma": "The platform",
  "Novedades": "News",
  "Socios": "Members",
  "Ejemplares": "Dogs",
  "Eventos": "Events",
  "Cargos y jueces": "Officers and judges",
  "Cría": "Breeding",
  "Aptos de cría": "Breeding qualifications",
  "Simulador de cruce": "Mating checker",
  "Camadas": "Litters",
  "Cruces intervariedades": "Inter-variety matings",
  "Mi área": "My area",
  "Mi perfil": "My profile",
  "Mi cuenta": "My account",
  "Cuota y pagos": "Fees and payments",
  "Administración": "Administration",
  "Panel de la junta": "Committee dashboard",
  "Validaciones": "Approvals",
  "Vídeos por publicar": "Videos awaiting approval",
  "Invitaciones": "Invitations",
  "Vinculación de altas": "Account linking",
  "Cuotas y cobros": "Fees and collections",
  "Administradores": "Administrators",
  "Diagnóstico": "Diagnostics",

  "Resumen": "Summary",
  "Salud y genética": "Health and genetics",
  "Resultados": "Results",
  "Pedigrí": "Pedigree",
  "Descendencia": "Offspring",
  "Fotos y vídeos": "Photos and videos",
  "Ficha del ejemplar": "Dog record",
  "Editar ficha": "Edit record",
  "Certificado del club": "Club certificate",
  "Dar de alta un ejemplar": "Register a dog",
  "Consanguinidad": "Inbreeding",
  "Generaciones conocidas": "Known generations",
  "Pedigrí completo": "Pedigree completeness",
  "Ancestros repetidos": "Repeated ancestors",

  "Validado": "Approved",
  "Rechazado": "Rejected",
  "Pendiente de validar": "Awaiting approval",
  "Completo": "Complete",
  "Excluido": "Excluded",
  "Cumple": "Meets",
  "Macho": "Male",
  "Hembra": "Female",
  "Junta directiva": "Committee",
  "Socio": "Member",
  "Visitante": "Visitor",

  "Guardar": "Save",
  "Cancelar": "Cancel",
  "Cerrar": "Close",
  "Editar": "Edit",
  "Borrar": "Delete",
  "Publicar": "Publish",
  "Entrar": "Sign in",
  "Salir": "Sign out",
  "Cerrar sesión": "Sign out",
  "Volver a la ficha": "Back to the record",
  "Subir foto": "Upload photo",
  "Subir vídeo": "Upload video",
  "Tema": "Theme",

  "No aparecer": "Do not appear",
  "Sólo socios": "Members only",
  "Cualquiera": "Anyone",
  "Público": "Public",
  "Privado": "Private",
  "Quién te ve": "Who can see you",
  "Contraseña": "Password",
  "Correo": "Email",
  "Foto": "Photo",

  "Acceso de socios": "Member sign-in",
  "He olvidado la contraseña": "I forgot my password",
  "Es mi primera vez": "This is my first time",
  "El libro está en blanco": "The studbook is empty",
  "Sin resultados": "No matches",
  "EN DIRECTO": "LIVE",
  "Club Español del Perro Pastor Belga": "Spanish Belgian Shepherd Dog Club",
  "Libro de Cría": "Studbook",

  /* Pantalla de bienvenida */
  "Guía rápida": "Quick guide",
  "Bienvenido al Libro de Cría": "Welcome to the Studbook",
  "Qué puedes hacer aquí y por dónde se empieza": "What you can do here and where to start",
  "Da de alta tus ejemplares": "Register your dogs",
  "Nombre y afijo tal como figuran en el pedigrí, LOE, chip y fecha de nacimiento. La ficha es tuya: nadie más la edita.": "Name and kennel name exactly as they appear on the pedigree, LOE number, microchip and date of birth. The record is yours: nobody else edits it.",
  "Ir a Ejemplares": "Go to Dogs",
  "Y su pedigrí se construye solo": "And the pedigree builds itself",
  "Escribes el padre y la madre; si ya están en el libro, el árbol crece hasta cinco generaciones sin que tengas que teclear nada más. Y si no los tenemos, puedes empezar por los abuelos.": "You enter the sire and the dam; if they are already in the studbook, the tree grows to five generations without you typing anything else. And if we do not have them, you can start from the grandparents.",
  "Ver el libro genealógico": "See the studbook",
  "Registra la salud y los títulos": "Record health results and titles",
  "Caderas, codos, LVT, las cuatro pruebas genéticas del Anexo A y el ADN. Los introduces tú, con tus certificados en la mano, y después el club los valida uno por uno.": "Hips, elbows, LVT, the four genetic tests in Annex A and the DNA profile. You enter them with your certificates in hand, and the club then validates them one by one.",
  "Empezar por un ejemplar": "Start with one dog",
  "Mira qué te falta para el apto de cría": "See what is missing for a breeding qualification",
  "El Reglamento de Cría de enero de 2025 está aplicado sobre cada ficha: las cinco figuras, con lo que ya cumple el perro y lo que le falta exactamente. Sin interpretaciones.": "The Breeding Regulations of January 2025 are applied to every record: the five qualifications, showing what the dog already meets and exactly what is missing. No interpretation needed.",
  "Calcula el cruce antes de hacerlo": "Work out the mating before you do it",
  "Eliges macho y hembra y la plataforma te dice la consanguinidad prevista de la camada, la profundidad del pedigrí y qué antepasados se repiten en ambas líneas. Antes de cubrir, no después.": "Pick a dog and a bitch and the platform gives you the expected inbreeding of the litter, the depth of the pedigree and which ancestors appear on both sides. Before the mating, not after.",
  "Descárgate el certificado del club": "Download the club certificate",
  "Un documento firmado con el emblema del CEPPB que reúne los títulos, el expediente de salud y los aptos de cría de tu perro. Sólo puede sacarlo su propietario.": "A signed document bearing the CEPPB emblem that brings together your dog's titles, health record and breeding qualifications. Only the owner can issue it.",
  "Desde la ficha del ejemplar": "From the dog's record",
  "Sube fotos y vídeos": "Upload photos and videos",
  "Las fotos van a la galería de la ficha. Los vídeos, hasta cinco minutos, pasan por el club y de ahí al canal de YouTube del CEPPB.": "Photos go into the record's gallery. Videos, up to five minutes, go through the club and from there to the CEPPB YouTube channel.",
  "Galería del ejemplar": "The dog's gallery",
  "Sigue los campeonatos": "Follow the championships",
  "El palmarés de los Campeonatos Nacionales de IGP, con puesto, puntos y guía de cada participación. Y las retransmisiones en directo, cuando las haya.": "The record of the National IGP Championships, with the placing, points and handler for every entry. And the live broadcasts, whenever there are any.",
  "Eventos y directos": "Events and live streams",
  "Tú decides qué se ve de ti": "You decide what is seen of you",
  "Tu perfil nace reservado: ningún socio sabe siquiera que existe hasta que tú lo abras, y eliges dato por dato qué compartes. El número de cuenta no se comparte nunca, con nadie.": "Your profile starts private: no member even knows it exists until you open it, and you choose field by field what you share. Your bank account is never shared, with anyone.",
  "Bienvenido, ": "Welcome, ",
  "Te damos la bienvenida": "Welcome",
  "El club deja de llevar sus perros en carpetas y hojas sueltas. Esto es un libro de cría vivo: el pedigrí se construye solo, el reglamento se aplica sobre cada ficha y la consanguinidad se calcula antes de cruzar, no después.": "The club no longer keeps its dogs in folders and loose sheets. This is a living studbook: the pedigree builds itself, the regulations are applied to every record and inbreeding is worked out before the mating, not after.",
  "Libro genealógico": "Studbook",
  "ejemplares enlazados entre sí": "dogs linked to one another",
  "Generaciones": "Generations",
  "de pedigrí desplegado": "of pedigree displayed",
  "Palmarés": "Record of results",
  "participaciones en campeonatos": "championship entries",
  "Reglamento": "Regulations",
  "aplicado ficha por ficha": "applied record by record",
  "Nueve cosas que puedes hacer desde hoy": "Nine things you can do from today",
  "La regla que sostiene todo lo demás": "The rule everything else rests on",
  "Detalles prácticos": "Practical details",
  "Desde el móvil": "On a phone",
  "Funciona igual que en el ordenador.": "It works just as it does on a computer.",
  "Idioma": "Language",
  "Empezar por mis ejemplares": "Start with my dogs",
  "Ver las novedades del club": "See the club news",

  /* Portada pública */
  "El libro genealógico del club: los ejemplares, sus pedigríes, su salud y sus títulos, con el Reglamento de Cría aplicado sobre cada ficha.": "The club's studbook: the dogs, their pedigrees, their health and their titles, with the Breeding Regulations applied to every record.",
  "Para los socios del CEPPB": "For CEPPB members",
  "Esto es de uso interno del club. Cada socio entra con su correo y ve su propia área; lo que aparece en ella depende de lo que cada uno haya decidido compartir.": "This is for the club's own use. Each member signs in with their email and sees their own area; what appears there depends on what each person has chosen to share.",
  "Si eres socio del club, tu ficha ya existe con los datos que constan en secretaría. Entra con tu correo para tomar posesión de ella.": "If you are a member, your record already exists with the details held by the club office. Sign in with your email to claim it.",
  "¿Todavía no eres socio?": "Not a member yet?",
  "El Club Español del Perro Pastor Belga reúne a los criadores, deportistas y aficionados de las cuatro variedades del pastor belga. Escribe a la secretaría del club y te explicamos cómo asociarte.": "The Spanish Belgian Shepherd Dog Club brings together the breeders, competitors and enthusiasts of the four Belgian Shepherd varieties. Write to the club office and we will explain how to join.",

  /* Eventos: el calendario de la web del club */
  "Convocatorias del libro": "Studbook events",
  "Calendario del CEPPB": "CEPPB calendar",
  "Abrir en una pestaña nueva": "Open in a new tab",
  "Esto es la página de eventos de la web del club, tal cual. Las inscripciones se hacen ahí.": "This is the club website's events page as it is. Entries are made there.",
  "Resultados de los eventos": "Event results",
  "Puesto": "Place",
  "Ejemplar": "Dog",
  "Guía": "Handler",
  "Puntos": "Points",
  "Calificación": "Grade",

  /* Instalarla en el teléfono */
  "En tu pantalla de inicio": "On your home screen",
  "Ya la estás usando como aplicación.": "You are already using it as an app.",
  "Llévala en el teléfono": "Take it with you on your phone",
  "Sin descargar nada": "Nothing to download",
  "Queda con el emblema del club en tu pantalla de inicio y se abre a pantalla completa, como cualquier otra aplicación. Es esta misma página: no ocupa apenas nada y se actualiza sola.": "It sits on your home screen with the club emblem and opens full screen, like any other app. It is this same page: it takes up almost no room and updates itself.",
  "Instalar en este dispositivo": "Install on this device",
  "Toca el botón de compartir, el cuadrado con la flecha hacia arriba.": "Tap the share button, the square with the arrow pointing up.",
  "Baja y elige «Añadir a pantalla de inicio».": "Scroll down and choose “Add to Home Screen”.",
  "Confirma. Te queda el emblema del club junto a tus demás aplicaciones.": "Confirm. The club emblem will sit alongside your other apps.",
  "Desde el menú de tu navegador, busca «Instalar aplicación» o «Añadir a pantalla de inicio».": "In your browser menu, look for “Install app” or “Add to Home Screen”.",
  "El Club Español del Perro Pastor Belga reúne a los criadores, deportistas y aficionados de las cuatro variedades del pastor belga.": "The Spanish Belgian Shepherd Dog Club brings together the breeders, competitors and enthusiasts of the four Belgian Shepherd varieties.",
  "Hazte socio": "Join the club",

  /* Los reglamentos */
  "Los reglamentos del club": "The club's regulations",
  "Toda la reglamentación": "All the regulations",
  "Descargar": "Download",
  "Reglamento de Cría del CEPPB": "CEPPB Breeding Regulations",
  "Anexo A · Salud": "Annex A · Health",
  "El texto completo: aptos de cría, figuras, edades, cruces intervariedades y baremos.": "The full text: breeding qualifications, the five categories, ages, inter-variety matings and scoring.",
  "Las pruebas exigidas y sus resultados válidos: caderas, codos, LVT, genética y ADN.": "The required tests and their valid results: hips, elbows, LVT, genetics and DNA.",
  "Lo que la plataforma aplica sobre cada ficha, en su texto original. Para leerlo o llevártelo.": "What the platform applies to every record, in its original wording. To read or to take with you.",

  /* Cuando el correo no consta en el censo */
  "Tu correo no consta en el censo": "Your email is not on the membership roll",
  "Has entrado con": "You signed in as",
  "y ese correo no figura en la ficha de ningún socio del club. El Libro de Cría es de uso interno: hasta que tu cuenta esté atada a una ficha del censo no se abre.": "and that address is not on any member's record. The Studbook is for the club's own use: until your account is linked to a record on the roll, it stays closed.",
  "Dos motivos suele haber:": "There are usually two reasons:",
  "La secretaría tiene otro correo tuyo. Escríbele y lo cambia, o entra con aquél.": "The club office has a different address for you. Write to them to change it, or sign in with that one.",
  "Todavía no eres socio del club.": "You are not a member of the club yet.",
  "¿Cuál de estas fichas es la tuya?": "Which of these records is yours?",
  "En el censo hay varias fichas con tu mismo correo, que es lo normal en una familia. Elige la tuya: sólo se ata una vez, así que asegúrate.": "There are several records on the roll with your email, which is normal in a family. Choose yours: it is linked only once, so make sure.",
  "Si ninguna es la tuya, escribe a la secretaría del club.": "If none of them is yours, write to the club office.",

  /* Me gusta y mensajes */
  "Me gusta": "Like",
  "Dile al propietario que te gusta": "Let the owner know you like it",
  "Ya te gusta. Púlsalo otra vez para quitarlo": "You already liked it. Press again to undo",
  "Escribir a su propietario": "Message the owner",
  "Escribirle": "Send a message",
  "Mensajes": "Messages",
  "Recibidos": "Inbox",
  "Enviados": "Sent",
  "Sin leer": "Unread",
  "Sin asunto": "No subject",
  "De": "From",
  "Para": "To",
  "Responder": "Reply",
  "Marcar leído": "Mark as read",
  "No tienes mensajes": "You have no messages",
  "Cuando otro socio te escriba desde tu perfil o desde la ficha de uno de tus perros, aparecerá aquí.": "When another member writes to you from your profile or from one of your dogs' records, it will appear here.",
  "No has escrito a nadie todavía": "You have not written to anyone yet",
  "Desde la ficha de un socio o de un ejemplar puedes escribir a su propietario.": "From a member's profile or a dog's record you can message the owner.",
  "Los socios se escriben aquí dentro, sin darse el correo. Si quieres darle el tuyo a alguien, se lo dices tú en el mensaje.": "Members write to each other in here, without exchanging email addresses. If you want to give someone yours, say so in the message.",
  "Nada con ese nombre": "Nothing by that name",

  /* Títulos, niveles y hermanos */
  "Títulos y niveles": "Titles and levels",
  "sin validar": "awaiting validation",
  "No cuentan hasta que la junta los coteja": "They do not count until the committee checks them",
  "Distinciones en concurso": "Show awards",
  "Todavía no hay ninguno validado por la junta.": "None validated by the committee yet.",
  "Hermanos": "Siblings",
};
