/* English. Kennel-club terms follow FCI usage: the breeding
   qualifications (ACE, ACES, ACU, ACUS, ACSS), Annex A and the
   variety names stay in their original form throughout the FCI. */
TEXTOS.en = {
  "La plataforma": "The platform",
  "Novedades": "News",
  "Socios": "Members",
  "Ejemplares": "Dogs",
  "Eventos": "Events",
  "Cargos y jueces": "Officers and judges",
  "Cría": "Breeding",
  "Aptos de cría": "Breeding qualifications",
  "Simulador de cruce": "Mating checker",
  "Camadas": "Litters",
  "Cruces intervariedades": "Inter-variety matings",
  "Mi área": "My area",
  "Mi perfil": "My profile",
  "Mi cuenta": "My account",
  "Cuota y pagos": "Fees and payments",
  "Administración": "Administration",
  "Panel de la junta": "Committee dashboard",
  "Validaciones": "Approvals",
  "Vídeos por publicar": "Videos awaiting approval",
  "Invitaciones": "Invitations",
  "Vinculación de altas": "Account linking",
  "Cuotas y cobros": "Fees and collections",
  "Administradores": "Administrators",
  "Diagnóstico": "Diagnostics",

  "Resumen": "Summary",
  "Salud y genética": "Health and genetics",
  "Resultados": "Results",
  "Pedigrí": "Pedigree",
  "Descendencia": "Offspring",
  "Fotos y vídeos": "Photos and videos",
  "Ficha del ejemplar": "Dog record",
  "Editar ficha": "Edit record",
  "Certificado del club": "Club certificate",
  "Dar de alta un ejemplar": "Register a dog",
  "Consanguinidad": "Inbreeding",
  "Generaciones conocidas": "Known generations",
  "Pedigrí completo": "Pedigree completeness",
  "Ancestros repetidos": "Repeated ancestors",

  "Validado": "Approved",
  "Rechazado": "Rejected",
  "Pendiente de validar": "Awaiting approval",
  "Completo": "Complete",
  "Excluido": "Excluded",
  "Cumple": "Meets",
  "Macho": "Male",
  "Hembra": "Female",
  "Junta directiva": "Committee",
  "Socio": "Member",
  "Visitante": "Visitor",

  "Guardar": "Save",
  "Cancelar": "Cancel",
  "Cerrar": "Close",
  "Editar": "Edit",
  "Borrar": "Delete",
  "Publicar": "Publish",
  "Entrar": "Sign in",
  "Salir": "Sign out",
  "Cerrar sesión": "Sign out",
  "Volver a la ficha": "Back to the record",
  "Subir foto": "Upload photo",
  "Subir vídeo": "Upload video",
  "Tema": "Theme",

  "No aparecer": "Do not appear",
  "Sólo socios": "Members only",
  "Cualquiera": "Anyone",
  "Público": "Public",
  "Privado": "Private",
  "Quién te ve": "Who can see you",
  "Contraseña": "Password",
  "Correo": "Email",
  "Foto": "Photo",

  "Acceso de socios": "Member sign-in",
  "He olvidado la contraseña": "I forgot my password",
  "Es mi primera vez": "This is my first time",
  "El libro está en blanco": "The studbook is empty",
  "Sin resultados": "No matches",
  "EN DIRECTO": "LIVE",
  "Club Español del Perro Pastor Belga": "Spanish Belgian Shepherd Dog Club",
  "Libro de Cría": "Studbook",
};
