/* Euskara batua. Erregelamenduko terminoak (ACE, ACES, ACU, ACUS,
   ACSS, A Eranskina), aldaeren izenak eta txakurren, afixen eta
   hazleen izen bereziak ez dira itzultzen: berberak dira FCI osoan. */
TEXTOS.eu = {
  "La plataforma": "Plataforma",
  "Novedades": "Berritasunak",
  "Socios": "Bazkideak",
  "Ejemplares": "Aleak",
  "Eventos": "Ekitaldiak",
  "Cargos y jueces": "Karguak eta epaileak",
  "Cría": "Hazkuntza",
  "Aptos de cría": "Hazkuntzarako gaitasunak",
  "Simulador de cruce": "Gurutzaketa simulagailua",
  "Camadas": "Kumaldiak",
  "Cruces intervariedades": "Aldaeren arteko gurutzaketak",
  "Mi área": "Nire eremua",
  "Mi perfil": "Nire profila",
  "Mi cuenta": "Nire kontua",
  "Cuota y pagos": "Kuota eta ordainketak",
  "Administración": "Administrazioa",
  "Panel de la junta": "Zuzendaritzaren panela",
  "Validaciones": "Balidazioak",
  "Vídeos por publicar": "Argitaratzeko bideoak",
  "Invitaciones": "Gonbidapenak",
  "Vinculación de altas": "Alten lotura",
  "Cuotas y cobros": "Kuotak eta kobrantzak",
  "Administradores": "Administratzaileak",
  "Diagnóstico": "Diagnostikoa",
  "Resumen": "Laburpena",
  "Salud y genética": "Osasuna eta genetika",
  "Resultados": "Emaitzak",
  "Pedigrí": "Pedigria",
  "Descendencia": "Ondorengoak",
  "Fotos y vídeos": "Argazkiak eta bideoak",
  "Ficha del ejemplar": "Alearen fitxa",
  "Editar ficha": "Editatu fitxa",
  "Certificado del club": "Klubaren ziurtagiria",
  "Dar de alta un ejemplar": "Eman alta ale bati",
  "Consanguinidad": "Odolkidetasuna",
  "Generaciones conocidas": "Belaunaldi ezagunak",
  "Pedigrí completo": "Pedigri osoa",
  "Ancestros repetidos": "Arbaso errepikatuak",
  "Validado": "Balioztatuta",
  "Rechazado": "Ezetsita",
  "Pendiente de validar": "Balioztatzeke",
  "Completo": "Osoa",
  "Excluido": "Kanpoan utzita",
  "Cumple": "Betetzen du",
  "Macho": "Arra",
  "Hembra": "Emea",
  "Junta directiva": "Zuzendaritza batzordea",
  "Socio": "Bazkidea",
  "Visitante": "Bisitaria",
  "Guardar": "Gorde",
  "Cancelar": "Utzi",
  "Cerrar": "Itxi",
  "Editar": "Editatu",
  "Borrar": "Ezabatu",
  "Publicar": "Argitaratu",
  "Entrar": "Sartu",
  "Salir": "Irten",
  "Cerrar sesión": "Amaitu saioa",
  "Volver a la ficha": "Itzuli fitxara",
  "Subir foto": "Igo argazkia",
  "Subir vídeo": "Igo bideoa",
  "Tema": "Gaia",
  "No aparecer": "Ez agertu",
  "Sólo socios": "Bazkideak soilik",
  "Cualquiera": "Edonor",
  "Público": "Publikoa",
  "Privado": "Pribatua",
  "Quién te ve": "Nork ikusten zaitu",
  "Contraseña": "Pasahitza",
  "Correo": "Helbide elektronikoa",
  "Foto": "Argazkia",
  "Acceso de socios": "Bazkideen sarbidea",
  "He olvidado la contraseña": "Pasahitza ahaztu zait",
  "Es mi primera vez": "Nire lehen aldia da",
  "El libro está en blanco": "Liburua hutsik dago",
  "Sin resultados": "Emaitzarik ez",
  "EN DIRECTO": "ZUZENEAN",
  "Club Español del Perro Pastor Belga": "Belgikako Artzain Txakurraren Espainiako Kluba",
  "Libro de Cría": "Hazkuntza Liburua",

  /* Pantalla de bienvenida */
  "Guía rápida": "Gida azkarra",
  "Bienvenido al Libro de Cría": "Ongi etorri Hazkuntza Liburura",
  "Qué puedes hacer aquí y por dónde se empieza": "Zer egin dezakezu hemen eta nondik hasi",
  "Da de alta tus ejemplares": "Eman alta zure aleei",
  "Nombre y afijo tal como figuran en el pedigrí, LOE, chip y fecha de nacimiento. La ficha es tuya: nadie más la edita.": "Izena eta afixua pedigrian ageri diren bezala, LOE zenbakia, txipa eta jaiotze-data. Fitxa zurea da: beste inork ez du editatzen.",
  "Ir a Ejemplares": "Joan Aleetara",
  "Y su pedigrí se construye solo": "Eta bere pedigria bakarrik eraikitzen da",
  "Escribes el padre y la madre; si ya están en el libro, el árbol crece hasta cinco generaciones sin que tengas que teclear nada más. Y si no los tenemos, puedes empezar por los abuelos.": "Aita eta ama idazten dituzu; liburuan badaude jada, zuhaitza bost belaunaldiraino hazten da ezer gehiago idatzi gabe. Eta haiek ez baditugu, aitona-amonetatik has zaitezke.",
  "Ver el libro genealógico": "Ikusi liburu genealogikoa",
  "Registra la salud y los títulos": "Erregistratu osasuna eta tituluak",
  "Caderas, codos, LVT, las cuatro pruebas genéticas del Anexo A y el ADN. Los introduces tú, con tus certificados en la mano, y después el club los valida uno por uno.": "Aldakak, ukondoak, LVT, A Eranskineko lau proba genetikoak eta DNA. Zuk sartzen dituzu, zure ziurtagiriak eskuan, eta gero klubak banan-banan balioztatzen ditu.",
  "Empezar por un ejemplar": "Hasi ale batekin",
  "Mira qué te falta para el apto de cría": "Ikusi zer falta zaizun hazkuntzarako gaitasunerako",
  "El Reglamento de Cría de enero de 2025 está aplicado sobre cada ficha: las cinco figuras, con lo que ya cumple el perro y lo que le falta exactamente. Sin interpretaciones.": "2025eko urtarrileko Hazkuntza Erregelamendua fitxa bakoitzari aplikatuta dago: bost figurak, txakurrak dagoeneko betetzen duenarekin eta zehazki falta zaionarekin. Interpretaziorik gabe.",
  "Calcula el cruce antes de hacerlo": "Kalkulatu gurutzaketa egin aurretik",
  "Eliges macho y hembra y la plataforma te dice la consanguinidad prevista de la camada, la profundidad del pedigrí y qué antepasados se repiten en ambas líneas. Antes de cubrir, no después.": "Arra eta emea aukeratzen dituzu eta plataformak kumaldiaren aurreikusitako odolkidetasuna, pedigriaren sakonera eta bi lerroetan errepikatzen diren arbasoak esaten dizkizu. Estali aurretik, ez ondoren.",
  "Descárgate el certificado del club": "Deskargatu klubaren ziurtagiria",
  "Un documento firmado con el emblema del CEPPB que reúne los títulos, el expediente de salud y los aptos de cría de tu perro. Sólo puede sacarlo su propietario.": "CEPPBren ikurrarekin sinatutako agiri bat, zure txakurraren tituluak, osasun-espedientea eta hazkuntzarako gaitasunak biltzen dituena. Jabeak bakarrik atera dezake.",
  "Desde la ficha del ejemplar": "Alearen fitxatik",
  "Sube fotos y vídeos": "Igo argazkiak eta bideoak",
  "Las fotos van a la galería de la ficha. Los vídeos, hasta cinco minutos, pasan por el club y de ahí al canal de YouTube del CEPPB.": "Argazkiak fitxaren galeriara doaz. Bideoak, bost minutura arte, klubetik pasatzen dira eta handik CEPPBren YouTube kanalera.",
  "Galería del ejemplar": "Alearen galeria",
  "Sigue los campeonatos": "Jarraitu txapelketak",
  "El palmarés de los Campeonatos Nacionales de IGP, con puesto, puntos y guía de cada participación. Y las retransmisiones en directo, cuando las haya.": "IGP Txapelketa Nazionalen palmaresa, parte-hartze bakoitzaren postuarekin, puntuekin eta gidariarekin. Eta zuzeneko emanaldiak, daudenean.",
  "Eventos y directos": "Ekitaldiak eta zuzenekoak",
  "Tú decides qué se ve de ti": "Zuk erabakitzen duzu zer ikusten den zutaz",
  "Tu perfil nace reservado: ningún socio sabe siquiera que existe hasta que tú lo abras, y eliges dato por dato qué compartes. El número de cuenta no se comparte nunca, con nadie.": "Zure profila itxita jaiotzen da: bazkide batek ere ez daki existitzen denik zuk ireki arte, eta datuz datu aukeratzen duzu zer partekatzen duzun. Kontu-zenbakia ez da inoiz partekatzen, inorekin.",
  "Bienvenido, ": "Ongi etorri, ",
  "Te damos la bienvenida": "Ongi etorri",
  "El club deja de llevar sus perros en carpetas y hojas sueltas. Esto es un libro de cría vivo: el pedigrí se construye solo, el reglamento se aplica sobre cada ficha y la consanguinidad se calcula antes de cruzar, no después.": "Klubak ez ditu gehiago bere txakurrak karpetatan eta orri solteetan eramango. Hau hazkuntza liburu bizia da: pedigria bakarrik eraikitzen da, erregelamendua fitxa bakoitzari aplikatzen zaio eta odolkidetasuna gurutzatu aurretik kalkulatzen da, ez ondoren.",
  "Libro genealógico": "Liburu genealogikoa",
  "ejemplares enlazados entre sí": "elkarri lotutako aleak",
  "Generaciones": "Belaunaldiak",
  "de pedigrí desplegado": "pedigri zabalduko",
  "Palmarés": "Palmaresa",
  "participaciones en campeonatos": "txapelketetako parte-hartzeak",
  "Reglamento": "Erregelamendua",
  "aplicado ficha por ficha": "fitxaz fitxa aplikatuta",
  "Nueve cosas que puedes hacer desde hoy": "Gaurtik egin ditzakezun bederatzi gauza",
  "La regla que sostiene todo lo demás": "Gainerako guztiari eusten dion araua",
  "Detalles prácticos": "Xehetasun praktikoak",
  "Desde el móvil": "Mugikorretik",
  "Funciona igual que en el ordenador.": "Ordenagailuan bezala funtzionatzen du.",
  "Idioma": "Hizkuntza",
  "Empezar por mis ejemplares": "Hasi nire aleekin",
  "Ver las novedades del club": "Ikusi klubaren berritasunak",

  /* Portada pública */
  "El libro genealógico del club: los ejemplares, sus pedigríes, su salud y sus títulos, con el Reglamento de Cría aplicado sobre cada ficha.": "Klubaren liburu genealogikoa: aleak, haien pedigriak, haien osasuna eta haien tituluak, Hazkuntza Erregelamendua fitxa bakoitzari aplikatuta.",
  "Para los socios del CEPPB": "CEPPBko bazkideentzat",
  "Esto es de uso interno del club. Cada socio entra con su correo y ve su propia área; lo que aparece en ella depende de lo que cada uno haya decidido compartir.": "Hau klubaren barne erabilerarako da. Bazkide bakoitza bere helbide elektronikoarekin sartzen da eta bere eremua ikusten du; bertan agertzen dena bakoitzak partekatzea erabaki duenaren araberakoa da.",
  "Si eres socio del club, tu ficha ya existe con los datos que constan en secretaría. Entra con tu correo para tomar posesión de ella.": "Klubeko bazkidea bazara, zure fitxa jada badago idazkaritzan dauden datuekin. Sartu zure helbide elektronikoarekin haren jabetza hartzeko.",
  "¿Todavía no eres socio?": "Oraindik ez zara bazkidea?",
  "El Club Español del Perro Pastor Belga reúne a los criadores, deportistas y aficionados de las cuatro variedades del pastor belga. Escribe a la secretaría del club y te explicamos cómo asociarte.": "Belgikako Artzain Txakurraren Espainiako Klubak belgikar artzainaren lau aldaeretako hazleak, kirolariak eta zaleak biltzen ditu. Idatzi klubaren idazkaritzara eta nola elkartu azalduko dizugu.",

  /* Eventos: el calendario de la web del club */
  "Convocatorias del libro": "Liburuaren deialdiak",
  "Calendario del CEPPB": "CEPPBren egutegia",
  "Abrir en una pestaña nueva": "Ireki fitxa berri batean",
  "Esto es la página de eventos de la web del club, tal cual. Las inscripciones se hacen ahí.": "Hau klubaren webguneko ekitaldien orria da, dagoen bezala. Izen-emateak han egiten dira.",
  "Resultados de los eventos": "Ekitaldien emaitzak",
  "Puesto": "Postua",
  "Ejemplar": "Alea",
  "Guía": "Gidaria",
  "Puntos": "Puntuak",
  "Calificación": "Kalifikazioa",

  /* Instalarla en el teléfono */
  "En tu pantalla de inicio": "Zure hasierako pantailan",
  "Ya la estás usando como aplicación.": "Dagoeneko aplikazio gisa erabiltzen ari zara.",
  "Llévala en el teléfono": "Eraman ezazu mugikorrean",
  "Sin descargar nada": "Ezer deskargatu gabe",
  "Queda con el emblema del club en tu pantalla de inicio y se abre a pantalla completa, como cualquier otra aplicación. Es esta misma página: no ocupa apenas nada y se actualiza sola.": "Klubaren ikurrarekin geratzen da zure hasierako pantailan eta pantaila osoan irekitzen da, beste edozein aplikazio bezala. Orri hau bera da: ia lekurik ez du hartzen eta bere kabuz eguneratzen da.",
  "Instalar en este dispositivo": "Instalatu gailu honetan",
  "Toca el botón de compartir, el cuadrado con la flecha hacia arriba.": "Ukitu partekatzeko botoia, gora begira dagoen gezidun karratua.",
  "Baja y elige «Añadir a pantalla de inicio».": "Jaitsi eta aukeratu «Gehitu hasierako pantailan».",
  "Confirma. Te queda el emblema del club junto a tus demás aplicaciones.": "Berretsi. Klubaren ikurra zure gainerako aplikazioen ondoan geratuko zaizu.",
  "Desde el menú de tu navegador, busca «Instalar aplicación» o «Añadir a pantalla de inicio».": "Zure nabigatzailearen menuan, bilatu «Instalatu aplikazioa» edo «Gehitu hasierako pantailan».",
  "El Club Español del Perro Pastor Belga reúne a los criadores, deportistas y aficionados de las cuatro variedades del pastor belga.": "Belgikako Artzain Txakurraren Espainiako Klubak belgikar artzainaren lau aldaeretako hazleak, kirolariak eta zaleak biltzen ditu.",
  "Hazte socio": "Egin zaitez bazkide",

  /* Los reglamentos */
  "Los reglamentos del club": "Klubaren erregelamenduak",
  "Toda la reglamentación": "Erregelamendu guztiak",
  "Descargar": "Deskargatu",
  "Reglamento de Cría del CEPPB": "CEPPBren Hazkuntza Erregelamendua",
  "Anexo A · Salud": "A Eranskina · Osasuna",
  "El texto completo: aptos de cría, figuras, edades, cruces intervariedades y baremos.": "Testu osoa: hazkuntzarako gaitasunak, bost figurak, adinak, aldaeren arteko gurutzaketak eta baremoak.",
  "Las pruebas exigidas y sus resultados válidos: caderas, codos, LVT, genética y ADN.": "Eskatzen diren probak eta haien emaitza baliagarriak: aldakak, ukondoak, LVT, genetika eta DNA.",
  "Lo que la plataforma aplica sobre cada ficha, en su texto original. Para leerlo o llevártelo.": "Plataformak fitxa bakoitzari aplikatzen diona, bere jatorrizko testuan. Irakurtzeko edo eramateko.",

  /* Cuando el correo no consta en el censo */
  "Tu correo no consta en el censo": "Zure helbidea ez dago bazkideen zerrendan",
  "Has entrado con": "Honekin sartu zara:",
  "y ese correo no figura en la ficha de ningún socio del club. El Libro de Cría es de uso interno: hasta que tu cuenta esté atada a una ficha del censo no se abre.": "eta helbide hori ez dago klubeko bazkide baten ere fitxan. Hazkuntza Liburua barne erabilerarako da: zure kontua zerrendako fitxa bati lotu arte, itxita dago.",
  "Dos motivos suele haber:": "Normalean bi arrazoi egoten dira:",
  "La secretaría tiene otro correo tuyo. Escríbele y lo cambia, o entra con aquél.": "Idazkaritzak beste helbide bat du zurea. Idatzi eta alda dezala, edo sartu harekin.",
  "Todavía no eres socio del club.": "Oraindik ez zara klubeko bazkidea.",
  "¿Cuál de estas fichas es la tuya?": "Fitxa hauetako zein da zurea?",
  "En el censo hay varias fichas con tu mismo correo, que es lo normal en una familia. Elige la tuya: sólo se ata una vez, así que asegúrate.": "Zerrendan hainbat fitxa daude zure helbide berarekin, familia batean ohikoa dena. Aukeratu zurea: behin bakarrik lotzen da, beraz, ziurtatu.",
  "Si ninguna es la tuya, escribe a la secretaría del club.": "Bat ere ez bada zurea, idatzi klubaren idazkaritzara.",

  /* Me gusta y mensajes */
  "Me gusta": "Gustatzen zait",
  "Dile al propietario que te gusta": "Esan jabeari gustatzen zaizula",
  "Ya te gusta. Púlsalo otra vez para quitarlo": "Dagoeneko gustatzen zaizu. Sakatu berriro kentzeko",
  "Escribir a su propietario": "Idatzi jabeari",
  "Escribirle": "Idatzi",
  "Mensajes": "Mezuak",
  "Recibidos": "Jasotakoak",
  "Enviados": "Bidalitakoak",
  "Sin leer": "Irakurri gabe",
  "Sin asunto": "Gairik gabe",
  "De": "Nork",
  "Para": "Nori",
  "Responder": "Erantzun",
  "Marcar leído": "Markatu irakurritzat",
  "No tienes mensajes": "Ez duzu mezurik",
  "Cuando otro socio te escriba desde tu perfil o desde la ficha de uno de tus perros, aparecerá aquí.": "Beste bazkide batek zure profiletik edo zure txakurren baten fitxatik idazten dizunean, hemen agertuko da.",
  "No has escrito a nadie todavía": "Oraindik ez diozu inori idatzi",
  "Desde la ficha de un socio o de un ejemplar puedes escribir a su propietario.": "Bazkide baten edo ale baten fitxatik bere jabeari idatz diezaiokezu.",
  "Los socios se escriben aquí dentro, sin darse el correo. Si quieres darle el tuyo a alguien, se lo dices tú en el mensaje.": "Bazkideek hemen barruan idazten diote elkarri, helbiderik eman gabe. Norbaiti zurea eman nahi badiozu, mezuan esan.",
  "Nada con ese nombre": "Ezer ez izen horrekin",
};
