/* Euskara batua. Erregelamenduko terminoak (ACE, ACES, ACU, ACUS,
   ACSS, A Eranskina), aldaeren izenak eta txakurren, afixen eta
   hazleen izen bereziak ez dira itzultzen: berberak dira FCI osoan. */
TEXTOS.eu = {
  "La plataforma": "Plataforma",
  "Novedades": "Berritasunak",
  "Socios": "Bazkideak",
  "Ejemplares": "Aleak",
  "Eventos": "Ekitaldiak",
  "Cargos y jueces": "Karguak eta epaileak",
  "Cría": "Hazkuntza",
  "Aptos de cría": "Hazkuntzarako gaitasunak",
  "Simulador de cruce": "Gurutzaketa simulagailua",
  "Camadas": "Kumaldiak",
  "Cruces intervariedades": "Aldaeren arteko gurutzaketak",
  "Mi área": "Nire eremua",
  "Mi perfil": "Nire profila",
  "Mi cuenta": "Nire kontua",
  "Cuota y pagos": "Kuota eta ordainketak",
  "Administración": "Administrazioa",
  "Panel de la junta": "Zuzendaritzaren panela",
  "Validaciones": "Balidazioak",
  "Vídeos por publicar": "Argitaratzeko bideoak",
  "Invitaciones": "Gonbidapenak",
  "Vinculación de altas": "Alten lotura",
  "Cuotas y cobros": "Kuotak eta kobrantzak",
  "Administradores": "Administratzaileak",
  "Diagnóstico": "Diagnostikoa",
  "Resumen": "Laburpena",
  "Salud y genética": "Osasuna eta genetika",
  "Resultados": "Emaitzak",
  "Pedigrí": "Pedigria",
  "Descendencia": "Ondorengoak",
  "Fotos y vídeos": "Argazkiak eta bideoak",
  "Ficha del ejemplar": "Alearen fitxa",
  "Editar ficha": "Editatu fitxa",
  "Certificado del club": "Klubaren ziurtagiria",
  "Dar de alta un ejemplar": "Eman alta ale bati",
  "Consanguinidad": "Odolkidetasuna",
  "Generaciones conocidas": "Belaunaldi ezagunak",
  "Pedigrí completo": "Pedigri osoa",
  "Ancestros repetidos": "Arbaso errepikatuak",
  "Validado": "Balioztatuta",
  "Rechazado": "Ezetsita",
  "Pendiente de validar": "Balioztatzeke",
  "Completo": "Osoa",
  "Excluido": "Kanpoan utzita",
  "Cumple": "Betetzen du",
  "Macho": "Arra",
  "Hembra": "Emea",
  "Junta directiva": "Zuzendaritza batzordea",
  "Socio": "Bazkidea",
  "Visitante": "Bisitaria",
  "Guardar": "Gorde",
  "Cancelar": "Utzi",
  "Cerrar": "Itxi",
  "Editar": "Editatu",
  "Borrar": "Ezabatu",
  "Publicar": "Argitaratu",
  "Entrar": "Sartu",
  "Salir": "Irten",
  "Cerrar sesión": "Amaitu saioa",
  "Volver a la ficha": "Itzuli fitxara",
  "Subir foto": "Igo argazkia",
  "Subir vídeo": "Igo bideoa",
  "Tema": "Gaia",
  "No aparecer": "Ez agertu",
  "Sólo socios": "Bazkideak soilik",
  "Cualquiera": "Edonor",
  "Público": "Publikoa",
  "Privado": "Pribatua",
  "Quién te ve": "Nork ikusten zaitu",
  "Contraseña": "Pasahitza",
  "Correo": "Helbide elektronikoa",
  "Foto": "Argazkia",
  "Acceso de socios": "Bazkideen sarbidea",
  "He olvidado la contraseña": "Pasahitza ahaztu zait",
  "Es mi primera vez": "Nire lehen aldia da",
  "El libro está en blanco": "Liburua hutsik dago",
  "Sin resultados": "Emaitzarik ez",
  "EN DIRECTO": "ZUZENEAN",
  "Club Español del Perro Pastor Belga": "Belgikako Artzain Txakurraren Espainiako Kluba",
  "Libro de Cría": "Hazkuntza Liburua",

  /* Pantalla de bienvenida */
  "Guía rápida": "Gida azkarra",
  "Bienvenido al Libro de Cría": "Ongi etorri Hazkuntza Liburura",
  "Qué puedes hacer aquí y por dónde se empieza": "Zer egin dezakezu hemen eta nondik hasi",
  "Da de alta tus ejemplares": "Eman alta zure aleei",
  "Nombre y afijo tal como figuran en el pedigrí, LOE, chip y fecha de nacimiento. La ficha es tuya: nadie más la edita.": "Izena eta afixua pedigrian ageri diren bezala, LOE zenbakia, txipa eta jaiotze-data. Fitxa zurea da: beste inork ez du editatzen.",
  "Ir a Ejemplares": "Joan Aleetara",
  "Y su pedigrí se construye solo": "Eta bere pedigria bakarrik eraikitzen da",
  "Escribes el padre y la madre; si ya están en el libro, el árbol crece hasta cinco generaciones sin que tengas que teclear nada más. Y si no los tenemos, puedes empezar por los abuelos.": "Aita eta ama idazten dituzu; liburuan badaude jada, zuhaitza bost belaunaldiraino hazten da ezer gehiago idatzi gabe. Eta haiek ez baditugu, aitona-amonetatik has zaitezke.",
  "Ver el libro genealógico": "Ikusi liburu genealogikoa",
  "Registra la salud y los títulos": "Erregistratu osasuna eta tituluak",
  "Caderas, codos, LVT, las cuatro pruebas genéticas del Anexo A y el ADN. Los introduces tú, con tus certificados en la mano, y después el club los valida uno por uno.": "Aldakak, ukondoak, LVT, A Eranskineko lau proba genetikoak eta DNA. Zuk sartzen dituzu, zure ziurtagiriak eskuan, eta gero klubak banan-banan balioztatzen ditu.",
  "Empezar por un ejemplar": "Hasi ale batekin",
  "Mira qué te falta para el apto de cría": "Ikusi zer falta zaizun hazkuntzarako gaitasunerako",
  "El Reglamento de Cría de enero de 2025 está aplicado sobre cada ficha: las cinco figuras, con lo que ya cumple el perro y lo que le falta exactamente. Sin interpretaciones.": "2025eko urtarrileko Hazkuntza Erregelamendua fitxa bakoitzari aplikatuta dago: bost figurak, txakurrak dagoeneko betetzen duenarekin eta zehazki falta zaionarekin. Interpretaziorik gabe.",
  "Calcula el cruce antes de hacerlo": "Kalkulatu gurutzaketa egin aurretik",
  "Eliges macho y hembra y la plataforma te dice la consanguinidad prevista de la camada, la profundidad del pedigrí y qué antepasados se repiten en ambas líneas. Antes de cubrir, no después.": "Arra eta emea aukeratzen dituzu eta plataformak kumaldiaren aurreikusitako odolkidetasuna, pedigriaren sakonera eta bi lerroetan errepikatzen diren arbasoak esaten dizkizu. Estali aurretik, ez ondoren.",
  "Descárgate el certificado del club": "Deskargatu klubaren ziurtagiria",
  "Un documento firmado con el emblema del CEPPB que reúne los títulos, el expediente de salud y los aptos de cría de tu perro. Sólo puede sacarlo su propietario.": "CEPPBren ikurrarekin sinatutako agiri bat, zure txakurraren tituluak, osasun-espedientea eta hazkuntzarako gaitasunak biltzen dituena. Jabeak bakarrik atera dezake.",
  "Desde la ficha del ejemplar": "Alearen fitxatik",
  "Sube fotos y vídeos": "Igo argazkiak eta bideoak",
  "Las fotos van a la galería de la ficha. Los vídeos, hasta cinco minutos, pasan por el club y de ahí al canal de YouTube del CEPPB.": "Argazkiak fitxaren galeriara doaz. Bideoak, bost minutura arte, klubetik pasatzen dira eta handik CEPPBren YouTube kanalera.",
  "Galería del ejemplar": "Alearen galeria",
  "Sigue los campeonatos": "Jarraitu txapelketak",
  "El palmarés de los Campeonatos Nacionales de IGP, con puesto, puntos y guía de cada participación. Y las retransmisiones en directo, cuando las haya.": "IGP Txapelketa Nazionalen palmaresa, parte-hartze bakoitzaren postuarekin, puntuekin eta gidariarekin. Eta zuzeneko emanaldiak, daudenean.",
  "Eventos y directos": "Ekitaldiak eta zuzenekoak",
  "Tú decides qué se ve de ti": "Zuk erabakitzen duzu zer ikusten den zutaz",
  "Tu perfil nace reservado: ningún socio sabe siquiera que existe hasta que tú lo abras, y eliges dato por dato qué compartes. El número de cuenta no se comparte nunca, con nadie.": "Zure profila itxita jaiotzen da: bazkide batek ere ez daki existitzen denik zuk ireki arte, eta datuz datu aukeratzen duzu zer partekatzen duzun. Kontu-zenbakia ez da inoiz partekatzen, inorekin.",
  "Bienvenido, ": "Ongi etorri, ",
  "Te damos la bienvenida": "Ongi etorri",
  "El club deja de llevar sus perros en carpetas y hojas sueltas. Esto es un libro de cría vivo: el pedigrí se construye solo, el reglamento se aplica sobre cada ficha y la consanguinidad se calcula antes de cruzar, no después.": "Klubak ez ditu gehiago bere txakurrak karpetatan eta orri solteetan eramango. Hau hazkuntza liburu bizia da: pedigria bakarrik eraikitzen da, erregelamendua fitxa bakoitzari aplikatzen zaio eta odolkidetasuna gurutzatu aurretik kalkulatzen da, ez ondoren.",
  "Libro genealógico": "Liburu genealogikoa",
  "ejemplares enlazados entre sí": "elkarri lotutako aleak",
  "Generaciones": "Belaunaldiak",
  "de pedigrí desplegado": "pedigri zabalduko",
  "Palmarés": "Palmaresa",
  "participaciones en campeonatos": "txapelketetako parte-hartzeak",
  "Reglamento": "Erregelamendua",
  "aplicado ficha por ficha": "fitxaz fitxa aplikatuta",
  "Nueve cosas que puedes hacer desde hoy": "Gaurtik egin ditzakezun bederatzi gauza",
  "La regla que sostiene todo lo demás": "Gainerako guztiari eusten dion araua",
  "Detalles prácticos": "Xehetasun praktikoak",
  "Desde el móvil": "Mugikorretik",
  "Funciona igual que en el ordenador.": "Ordenagailuan bezala funtzionatzen du.",
  "Idioma": "Hizkuntza",
  "Empezar por mis ejemplares": "Hasi nire aleekin",
  "Ver las novedades del club": "Ikusi klubaren berritasunak",
};
