/* Français. Les termes du règlement d'élevage (ACE, ACES, ACU, ACUS,
   ACSS), l'Annexe A et les noms de variétés restent tels quels : ils
   sont identiques dans toute la FCI. */
TEXTOS.fr = {
  "La plataforma": "La plateforme",
  "Novedades": "Actualités",
  "Socios": "Membres",
  "Ejemplares": "Sujets",
  "Eventos": "Manifestations",
  "Cargos y jueces": "Responsables et juges",
  "Cría": "Élevage",
  "Aptos de cría": "Aptitudes à l'élevage",
  "Simulador de cruce": "Simulateur d'accouplement",
  "Camadas": "Portées",
  "Cruces intervariedades": "Croisements entre variétés",
  "Mi área": "Mon espace",
  "Mi perfil": "Mon profil",
  "Mi cuenta": "Mon compte",
  "Cuota y pagos": "Cotisation et paiements",
  "Administración": "Administration",
  "Panel de la junta": "Tableau du comité",
  "Validaciones": "Validations",
  "Vídeos por publicar": "Vidéos à publier",
  "Invitaciones": "Invitations",
  "Vinculación de altas": "Rattachement des comptes",
  "Cuotas y cobros": "Cotisations et encaissements",
  "Administradores": "Administrateurs",
  "Diagnóstico": "Diagnostic",

  "Resumen": "Résumé",
  "Salud y genética": "Santé et génétique",
  "Resultados": "Résultats",
  "Pedigrí": "Pedigree",
  "Descendencia": "Descendance",
  "Fotos y vídeos": "Photos et vidéos",
  "Ficha del ejemplar": "Fiche du sujet",
  "Editar ficha": "Modifier la fiche",
  "Certificado del club": "Certificat du club",
  "Dar de alta un ejemplar": "Enregistrer un sujet",
  "Consanguinidad": "Consanguinité",
  "Generaciones conocidas": "Générations connues",
  "Pedigrí completo": "Pedigree complet",
  "Ancestros repetidos": "Ancêtres répétés",

  "Validado": "Validé",
  "Rechazado": "Refusé",
  "Pendiente de validar": "En attente de validation",
  "Completo": "Complet",
  "Excluido": "Exclu",
  "Cumple": "Satisfait",
  "Macho": "Mâle",
  "Hembra": "Femelle",
  "Junta directiva": "Comité directeur",
  "Socio": "Membre",
  "Visitante": "Visiteur",

  "Guardar": "Enregistrer",
  "Cancelar": "Annuler",
  "Cerrar": "Fermer",
  "Editar": "Modifier",
  "Borrar": "Supprimer",
  "Publicar": "Publier",
  "Entrar": "Se connecter",
  "Salir": "Se déconnecter",
  "Cerrar sesión": "Se déconnecter",
  "Volver a la ficha": "Retour à la fiche",
  "Subir foto": "Envoyer une photo",
  "Subir vídeo": "Envoyer une vidéo",
  "Tema": "Thème",

  "No aparecer": "Ne pas apparaître",
  "Sólo socios": "Membres uniquement",
  "Cualquiera": "Tout le monde",
  "Público": "Public",
  "Privado": "Privé",
  "Quién te ve": "Qui vous voit",
  "Contraseña": "Mot de passe",
  "Correo": "Courriel",
  "Foto": "Photo",

  "Acceso de socios": "Accès des membres",
  "He olvidado la contraseña": "J'ai oublié mon mot de passe",
  "Es mi primera vez": "C'est ma première fois",
  "El libro está en blanco": "Le livre d'élevage est vide",
  "Sin resultados": "Aucun résultat",
  "EN DIRECTO": "EN DIRECT",
  "Club Español del Perro Pastor Belga": "Club Espagnol du Chien de Berger Belge",
  "Libro de Cría": "Livre d'élevage",
};
