/* Français. Les termes du règlement d'élevage (ACE, ACES, ACU, ACUS,
   ACSS), l'Annexe A et les noms de variétés restent tels quels : ils
   sont identiques dans toute la FCI. */
TEXTOS.fr = {
  "La plataforma": "La plateforme",
  "Novedades": "Actualités",
  "Socios": "Membres",
  "Ejemplares": "Sujets",
  "Eventos": "Manifestations",
  "Cargos y jueces": "Responsables et juges",
  "Cría": "Élevage",
  "Aptos de cría": "Aptitudes à l'élevage",
  "Simulador de cruce": "Simulateur d'accouplement",
  "Camadas": "Portées",
  "Cruces intervariedades": "Croisements entre variétés",
  "Mi área": "Mon espace",
  "Mi perfil": "Mon profil",
  "Mi cuenta": "Mon compte",
  "Cuota y pagos": "Cotisation et paiements",
  "Administración": "Administration",
  "Panel de la junta": "Tableau du comité",
  "Validaciones": "Validations",
  "Vídeos por publicar": "Vidéos à publier",
  "Invitaciones": "Invitations",
  "Vinculación de altas": "Rattachement des comptes",
  "Cuotas y cobros": "Cotisations et encaissements",
  "Administradores": "Administrateurs",
  "Diagnóstico": "Diagnostic",

  "Resumen": "Résumé",
  "Salud y genética": "Santé et génétique",
  "Resultados": "Résultats",
  "Pedigrí": "Pedigree",
  "Descendencia": "Descendance",
  "Fotos y vídeos": "Photos et vidéos",
  "Ficha del ejemplar": "Fiche du sujet",
  "Editar ficha": "Modifier la fiche",
  "Certificado del club": "Certificat du club",
  "Dar de alta un ejemplar": "Enregistrer un sujet",
  "Consanguinidad": "Consanguinité",
  "Generaciones conocidas": "Générations connues",
  "Pedigrí completo": "Pedigree complet",
  "Ancestros repetidos": "Ancêtres répétés",

  "Validado": "Validé",
  "Rechazado": "Refusé",
  "Pendiente de validar": "En attente de validation",
  "Completo": "Complet",
  "Excluido": "Exclu",
  "Cumple": "Satisfait",
  "Macho": "Mâle",
  "Hembra": "Femelle",
  "Junta directiva": "Comité directeur",
  "Socio": "Membre",
  "Visitante": "Visiteur",

  "Guardar": "Enregistrer",
  "Cancelar": "Annuler",
  "Cerrar": "Fermer",
  "Editar": "Modifier",
  "Borrar": "Supprimer",
  "Publicar": "Publier",
  "Entrar": "Se connecter",
  "Salir": "Se déconnecter",
  "Cerrar sesión": "Se déconnecter",
  "Volver a la ficha": "Retour à la fiche",
  "Subir foto": "Envoyer une photo",
  "Subir vídeo": "Envoyer une vidéo",
  "Tema": "Thème",

  "No aparecer": "Ne pas apparaître",
  "Sólo socios": "Membres uniquement",
  "Cualquiera": "Tout le monde",
  "Público": "Public",
  "Privado": "Privé",
  "Quién te ve": "Qui vous voit",
  "Contraseña": "Mot de passe",
  "Correo": "Courriel",
  "Foto": "Photo",

  "Acceso de socios": "Accès des membres",
  "He olvidado la contraseña": "J'ai oublié mon mot de passe",
  "Es mi primera vez": "C'est ma première fois",
  "El libro está en blanco": "Le livre d'élevage est vide",
  "Sin resultados": "Aucun résultat",
  "EN DIRECTO": "EN DIRECT",
  "Club Español del Perro Pastor Belga": "Club Espagnol du Chien de Berger Belge",
  "Libro de Cría": "Livre d'élevage",

  /* Pantalla de bienvenida */
  "Guía rápida": "Guide rapide",
  "Bienvenido al Libro de Cría": "Bienvenue dans le Livre d'Élevage",
  "Qué puedes hacer aquí y por dónde se empieza": "Ce que vous pouvez faire ici et par où commencer",
  "Da de alta tus ejemplares": "Enregistrez vos chiens",
  "Nombre y afijo tal como figuran en el pedigrí, LOE, chip y fecha de nacimiento. La ficha es tuya: nadie más la edita.": "Nom et affixe tels qu'ils figurent au pedigree, LOE, puce et date de naissance. La fiche est la vôtre : personne d'autre ne la modifie.",
  "Ir a Ejemplares": "Aller aux Chiens",
  "Y su pedigrí se construye solo": "Et son pedigree se construit tout seul",
  "Escribes el padre y la madre; si ya están en el libro, el árbol crece hasta cinco generaciones sin que tengas que teclear nada más. Y si no los tenemos, puedes empezar por los abuelos.": "Vous saisissez le père et la mère ; s'ils figurent déjà au livre, l'arbre s'étend jusqu'à cinq générations sans rien taper de plus. Et si nous ne les avons pas, vous pouvez commencer par les grands-parents.",
  "Ver el libro genealógico": "Voir le livre généalogique",
  "Registra la salud y los títulos": "Enregistrez la santé et les titres",
  "Caderas, codos, LVT, las cuatro pruebas genéticas del Anexo A y el ADN. Los introduces tú, con tus certificados en la mano, y después el club los valida uno por uno.": "Hanches, coudes, LVT, les quatre tests génétiques de l'Annexe A et l'ADN. C'est vous qui les saisissez, certificats en main, et le club les valide ensuite un par un.",
  "Empezar por un ejemplar": "Commencer par un chien",
  "Mira qué te falta para el apto de cría": "Voyez ce qu'il vous manque pour l'aptitude à l'élevage",
  "El Reglamento de Cría de enero de 2025 está aplicado sobre cada ficha: las cinco figuras, con lo que ya cumple el perro y lo que le falta exactamente. Sin interpretaciones.": "Le Règlement d'Élevage de janvier 2025 est appliqué à chaque fiche : les cinq catégories, avec ce que le chien remplit déjà et ce qui lui manque exactement. Sans interprétation.",
  "Calcula el cruce antes de hacerlo": "Calculez l'accouplement avant de le faire",
  "Eliges macho y hembra y la plataforma te dice la consanguinidad prevista de la camada, la profundidad del pedigrí y qué antepasados se repiten en ambas líneas. Antes de cubrir, no después.": "Vous choisissez le mâle et la femelle et la plateforme vous donne la consanguinité prévue de la portée, la profondeur du pedigree et quels ancêtres se répètent des deux côtés. Avant la saillie, pas après.",
  "Descárgate el certificado del club": "Téléchargez le certificat du club",
  "Un documento firmado con el emblema del CEPPB que reúne los títulos, el expediente de salud y los aptos de cría de tu perro. Sólo puede sacarlo su propietario.": "Un document signé portant l'emblème du CEPPB qui réunit les titres, le dossier de santé et les aptitudes à l'élevage de votre chien. Seul son propriétaire peut l'éditer.",
  "Desde la ficha del ejemplar": "Depuis la fiche du chien",
  "Sube fotos y vídeos": "Ajoutez photos et vidéos",
  "Las fotos van a la galería de la ficha. Los vídeos, hasta cinco minutos, pasan por el club y de ahí al canal de YouTube del CEPPB.": "Les photos vont dans la galerie de la fiche. Les vidéos, jusqu'à cinq minutes, passent par le club puis vers la chaîne YouTube du CEPPB.",
  "Galería del ejemplar": "Galerie du chien",
  "Sigue los campeonatos": "Suivez les championnats",
  "El palmarés de los Campeonatos Nacionales de IGP, con puesto, puntos y guía de cada participación. Y las retransmisiones en directo, cuando las haya.": "Le palmarès des Championnats Nationaux d'IGP, avec le classement, les points et le conducteur de chaque participation. Et les retransmissions en direct, quand il y en a.",
  "Eventos y directos": "Événements et directs",
  "Tú decides qué se ve de ti": "C'est vous qui décidez ce que l'on voit de vous",
  "Tu perfil nace reservado: ningún socio sabe siquiera que existe hasta que tú lo abras, y eliges dato por dato qué compartes. El número de cuenta no se comparte nunca, con nadie.": "Votre profil naît privé : aucun membre ne sait même qu'il existe tant que vous ne l'ouvrez pas, et vous choisissez donnée par donnée ce que vous partagez. Le numéro de compte n'est jamais partagé, avec personne.",
  "Bienvenido, ": "Bienvenue, ",
  "Te damos la bienvenida": "Bienvenue",
  "El club deja de llevar sus perros en carpetas y hojas sueltas. Esto es un libro de cría vivo: el pedigrí se construye solo, el reglamento se aplica sobre cada ficha y la consanguinidad se calcula antes de cruzar, no después.": "Le club cesse de tenir ses chiens dans des classeurs et des feuilles volantes. Voici un livre d'élevage vivant : le pedigree se construit tout seul, le règlement s'applique à chaque fiche et la consanguinité se calcule avant l'accouplement, pas après.",
  "Libro genealógico": "Livre généalogique",
  "ejemplares enlazados entre sí": "chiens reliés entre eux",
  "Generaciones": "Générations",
  "de pedigrí desplegado": "de pedigree déployé",
  "Palmarés": "Palmarès",
  "participaciones en campeonatos": "participations en championnat",
  "Reglamento": "Règlement",
  "aplicado ficha por ficha": "appliqué fiche par fiche",
  "Nueve cosas que puedes hacer desde hoy": "Neuf choses que vous pouvez faire dès aujourd'hui",
  "La regla que sostiene todo lo demás": "La règle qui soutient tout le reste",
  "Detalles prácticos": "Détails pratiques",
  "Desde el móvil": "Depuis le téléphone",
  "Funciona igual que en el ordenador.": "Cela fonctionne comme sur l'ordinateur.",
  "Idioma": "Langue",
  "Empezar por mis ejemplares": "Commencer par mes chiens",
  "Ver las novedades del club": "Voir les actualités du club",

  /* Portada pública */
  "El libro genealógico del club: los ejemplares, sus pedigríes, su salud y sus títulos, con el Reglamento de Cría aplicado sobre cada ficha.": "Le livre généalogique du club : les chiens, leurs pedigrees, leur santé et leurs titres, avec le Règlement d'Élevage appliqué à chaque fiche.",
  "Para los socios del CEPPB": "Pour les membres du CEPPB",
  "Esto es de uso interno del club. Cada socio entra con su correo y ve su propia área; lo que aparece en ella depende de lo que cada uno haya decidido compartir.": "C'est à usage interne du club. Chaque membre se connecte avec son adresse et voit son propre espace ; ce qui s'y affiche dépend de ce que chacun a choisi de partager.",
  "Si eres socio del club, tu ficha ya existe con los datos que constan en secretaría. Entra con tu correo para tomar posesión de ella.": "Si vous êtes membre du club, votre fiche existe déjà avec les données du secrétariat. Connectez-vous avec votre adresse pour en prendre possession.",
  "¿Todavía no eres socio?": "Pas encore membre ?",
  "El Club Español del Perro Pastor Belga reúne a los criadores, deportistas y aficionados de las cuatro variedades del pastor belga. Escribe a la secretaría del club y te explicamos cómo asociarte.": "Le Club Espagnol du Chien de Berger Belge réunit les éleveurs, les compétiteurs et les passionnés des quatre variétés du berger belge. Écrivez au secrétariat du club et nous vous expliquerons comment adhérer.",

  /* Eventos: el calendario de la web del club */
  "Convocatorias del libro": "Convocations du livre",
  "Calendario del CEPPB": "Calendrier du CEPPB",
  "Abrir en una pestaña nueva": "Ouvrir dans un nouvel onglet",
  "Esto es la página de eventos de la web del club, tal cual. Las inscripciones se hacen ahí.": "Voici la page des événements du site du club, telle quelle. Les inscriptions s'y font.",
};
