/* Galego, normativa RAG. Os termos do regulamento (ACE, ACES, ACU,
   ACUS, ACSS, Anexo A), os nomes das variedades e os nomes propios de
   cans, afixos e criadores non se traducen: son os mesmos en toda a
   FCI. */
TEXTOS.gl = {
  "La plataforma": "A plataforma",
  "Novedades": "Novidades",
  "Socios": "Socios",
  "Ejemplares": "Exemplares",
  "Eventos": "Eventos",
  "Cargos y jueces": "Cargos e xuíces",
  "Cría": "Cría",
  "Aptos de cría": "Aptos de cría",
  "Simulador de cruce": "Simulador de cruzamento",
  "Camadas": "Camadas",
  "Cruces intervariedades": "Cruzamentos entre variedades",
  "Mi área": "A miña área",
  "Mi perfil": "O meu perfil",
  "Mi cuenta": "A miña conta",
  "Cuota y pagos": "Cota e pagamentos",
  "Administración": "Administración",
  "Panel de la junta": "Panel da xunta",
  "Validaciones": "Validacións",
  "Vídeos por publicar": "Vídeos por publicar",
  "Invitaciones": "Invitacións",
  "Vinculación de altas": "Vinculación de altas",
  "Cuotas y cobros": "Cotas e cobramentos",
  "Administradores": "Administradores",
  "Diagnóstico": "Diagnóstico",
  "Resumen": "Resumo",
  "Salud y genética": "Saúde e xenética",
  "Resultados": "Resultados",
  "Pedigrí": "Pedigrí",
  "Descendencia": "Descendencia",
  "Fotos y vídeos": "Fotos e vídeos",
  "Ficha del ejemplar": "Ficha do exemplar",
  "Editar ficha": "Editar a ficha",
  "Certificado del club": "Certificado do club",
  "Dar de alta un ejemplar": "Dar de alta un exemplar",
  "Consanguinidad": "Consanguinidade",
  "Generaciones conocidas": "Xeracións coñecidas",
  "Pedigrí completo": "Pedigrí completo",
  "Ancestros repetidos": "Antepasados repetidos",
  "Validado": "Validado",
  "Rechazado": "Rexeitado",
  "Pendiente de validar": "Pendente de validar",
  "Completo": "Completo",
  "Excluido": "Excluído",
  "Cumple": "Cumpre",
  "Macho": "Macho",
  "Hembra": "Femia",
  "Junta directiva": "Xunta directiva",
  "Socio": "Socio",
  "Visitante": "Visitante",
  "Guardar": "Gardar",
  "Cancelar": "Cancelar",
  "Cerrar": "Pechar",
  "Editar": "Editar",
  "Borrar": "Borrar",
  "Publicar": "Publicar",
  "Entrar": "Entrar",
  "Salir": "Saír",
  "Cerrar sesión": "Pechar a sesión",
  "Volver a la ficha": "Volver á ficha",
  "Subir foto": "Subir unha foto",
  "Subir vídeo": "Subir un vídeo",
  "Tema": "Tema",
  "No aparecer": "Non aparecer",
  "Sólo socios": "Só socios",
  "Cualquiera": "Calquera",
  "Público": "Público",
  "Privado": "Privado",
  "Quién te ve": "Quen te ve",
  "Contraseña": "Contrasinal",
  "Correo": "Correo",
  "Foto": "Foto",
  "Acceso de socios": "Acceso de socios",
  "He olvidado la contraseña": "Esquecín o contrasinal",
  "Es mi primera vez": "É a miña primeira vez",
  "El libro está en blanco": "O libro está en branco",
  "Sin resultados": "Sen resultados",
  "EN DIRECTO": "EN DIRECTO",
  "Club Español del Perro Pastor Belga": "Club Español do Can Pastor Belga",
  "Libro de Cría": "Libro de Cría",

  /* Pantalla de bienvenida */
  "Guía rápida": "Guía rápida",
  "Bienvenido al Libro de Cría": "Benvido ao Libro de Cría",
  "Qué puedes hacer aquí y por dónde se empieza": "Que podes facer aquí e por onde se empeza",
  "Da de alta tus ejemplares": "Da de alta os teus exemplares",
  "Nombre y afijo tal como figuran en el pedigrí, LOE, chip y fecha de nacimiento. La ficha es tuya: nadie más la edita.": "Nome e afixo tal como figuran no pedigrí, LOE, chip e data de nacemento. A ficha é túa: ninguén máis a edita.",
  "Ir a Ejemplares": "Ir a Exemplares",
  "Y su pedigrí se construye solo": "E o seu pedigrí constrúese só",
  "Escribes el padre y la madre; si ya están en el libro, el árbol crece hasta cinco generaciones sin que tengas que teclear nada más. Y si no los tenemos, puedes empezar por los abuelos.": "Escribes o pai e a nai; se xa están no libro, a árbore medra ata cinco xeracións sen que teñas que teclear nada máis. E se non os temos, podes empezar polos avós.",
  "Ver el libro genealógico": "Ver o libro xenealóxico",
  "Registra la salud y los títulos": "Rexistra a saúde e os títulos",
  "Caderas, codos, LVT, las cuatro pruebas genéticas del Anexo A y el ADN. Los introduces tú, con tus certificados en la mano, y después el club los valida uno por uno.": "Cadeiras, cóbados, LVT, as catro probas xenéticas do Anexo A e mais o ADN. Introdúcelos ti, cos teus certificados na man, e despois o club valídaos un por un.",
  "Empezar por un ejemplar": "Empezar por un exemplar",
  "Mira qué te falta para el apto de cría": "Mira que che falta para o apto de cría",
  "El Reglamento de Cría de enero de 2025 está aplicado sobre cada ficha: las cinco figuras, con lo que ya cumple el perro y lo que le falta exactamente. Sin interpretaciones.": "O Regulamento de Cría de xaneiro de 2025 está aplicado sobre cada ficha: as cinco figuras, co que o can xa cumpre e o que lle falta exactamente. Sen interpretacións.",
  "Calcula el cruce antes de hacerlo": "Calcula o cruzamento antes de facelo",
  "Eliges macho y hembra y la plataforma te dice la consanguinidad prevista de la camada, la profundidad del pedigrí y qué antepasados se repiten en ambas líneas. Antes de cubrir, no después.": "Escolles macho e femia e a plataforma dime a consanguinidade prevista da camada, a profundidade do pedigrí e que antepasados se repiten nas dúas liñas. Antes de cubrir, non despois.",
  "Descárgate el certificado del club": "Descarga o certificado do club",
  "Un documento firmado con el emblema del CEPPB que reúne los títulos, el expediente de salud y los aptos de cría de tu perro. Sólo puede sacarlo su propietario.": "Un documento asinado co emblema do CEPPB que reúne os títulos, o expediente de saúde e os aptos de cría do teu can. Só o pode obter o seu propietario.",
  "Desde la ficha del ejemplar": "Desde a ficha do exemplar",
  "Sube fotos y vídeos": "Sobe fotos e vídeos",
  "Las fotos van a la galería de la ficha. Los vídeos, hasta cinco minutos, pasan por el club y de ahí al canal de YouTube del CEPPB.": "As fotos van á galería da ficha. Os vídeos, ata cinco minutos, pasan polo club e de aí á canle de YouTube do CEPPB.",
  "Galería del ejemplar": "Galería do exemplar",
  "Sigue los campeonatos": "Segue os campionatos",
  "El palmarés de los Campeonatos Nacionales de IGP, con puesto, puntos y guía de cada participación. Y las retransmisiones en directo, cuando las haya.": "O palmarés dos Campionatos Nacionais de IGP, co posto, os puntos e o guía de cada participación. E mais as retransmisións en directo, cando as haxa.",
  "Eventos y directos": "Eventos e directos",
  "Tú decides qué se ve de ti": "Ti decides que se ve de ti",
  "Tu perfil nace reservado: ningún socio sabe siquiera que existe hasta que tú lo abras, y eliges dato por dato qué compartes. El número de cuenta no se comparte nunca, con nadie.": "O teu perfil nace reservado: ningún socio sabe sequera que existe ata que ti o abras, e escolles dato por dato que compartes. O número de conta non se comparte nunca, con ninguén.",
  "Bienvenido, ": "Benvido, ",
  "Te damos la bienvenida": "Dámosche a benvida",
  "El club deja de llevar sus perros en carpetas y hojas sueltas. Esto es un libro de cría vivo: el pedigrí se construye solo, el reglamento se aplica sobre cada ficha y la consanguinidad se calcula antes de cruzar, no después.": "O club deixa de levar os seus cans en carpetas e follas soltas. Isto é un libro de cría vivo: o pedigrí constrúese só, o regulamento aplícase sobre cada ficha e a consanguinidade calcúlase antes de cruzar, non despois.",
  "Libro genealógico": "Libro xenealóxico",
  "ejemplares enlazados entre sí": "exemplares ligados entre si",
  "Generaciones": "Xeracións",
  "de pedigrí desplegado": "de pedigrí despregado",
  "Palmarés": "Palmarés",
  "participaciones en campeonatos": "participacións en campionatos",
  "Reglamento": "Regulamento",
  "aplicado ficha por ficha": "aplicado ficha por ficha",
  "Nueve cosas que puedes hacer desde hoy": "Nove cousas que podes facer desde hoxe",
  "La regla que sostiene todo lo demás": "A regra que sostén todo o demais",
  "Detalles prácticos": "Detalles prácticos",
  "Desde el móvil": "Desde o móbil",
  "Funciona igual que en el ordenador.": "Funciona igual ca no ordenador.",
  "Idioma": "Idioma",
  "Empezar por mis ejemplares": "Empezar polos meus exemplares",
  "Ver las novedades del club": "Ver as novidades do club",

  /* Portada pública */
  "El libro genealógico del club: los ejemplares, sus pedigríes, su salud y sus títulos, con el Reglamento de Cría aplicado sobre cada ficha.": "O libro xenealóxico do club: os exemplares, os seus pedigrís, a súa saúde e os seus títulos, co Regulamento de Cría aplicado sobre cada ficha.",
  "Para los socios del CEPPB": "Para os socios do CEPPB",
  "Esto es de uso interno del club. Cada socio entra con su correo y ve su propia área; lo que aparece en ella depende de lo que cada uno haya decidido compartir.": "Isto é de uso interno do club. Cada socio entra co seu correo e ve a súa propia área; o que aparece nela depende do que cadaquén decidise compartir.",
  "Si eres socio del club, tu ficha ya existe con los datos que constan en secretaría. Entra con tu correo para tomar posesión de ella.": "Se es socio do club, a túa ficha xa existe cos datos que constan na secretaría. Entra co teu correo para tomar posesión dela.",
  "¿Todavía no eres socio?": "Aínda non es socio?",
  "El Club Español del Perro Pastor Belga reúne a los criadores, deportistas y aficionados de las cuatro variedades del pastor belga. Escribe a la secretaría del club y te explicamos cómo asociarte.": "O Club Español do Can Pastor Belga reúne os criadores, deportistas e afeccionados das catro variedades do pastor belga. Escribe á secretaría do club e explicámosche como asociarte.",

  /* Eventos: el calendario de la web del club */
  "Convocatorias del libro": "Convocatorias do libro",
  "Calendario del CEPPB": "Calendario do CEPPB",
  "Abrir en una pestaña nueva": "Abrir nunha lapela nova",
  "Esto es la página de eventos de la web del club, tal cual. Las inscripciones se hacen ahí.": "Isto é a páxina de eventos da web do club, tal cal. As inscricións fanse alí.",
  "Resultados de los eventos": "Resultados dos eventos",
  "Puesto": "Posto",
  "Ejemplar": "Exemplar",
  "Guía": "Guía",
  "Puntos": "Puntos",
  "Calificación": "Cualificación",

  /* Instalarla en el teléfono */
  "En tu pantalla de inicio": "Na túa pantalla de inicio",
  "Ya la estás usando como aplicación.": "Xa a estás usando como aplicación.",
  "Llévala en el teléfono": "Lévaa no teléfono",
  "Sin descargar nada": "Sen descargar nada",
  "Queda con el emblema del club en tu pantalla de inicio y se abre a pantalla completa, como cualquier otra aplicación. Es esta misma página: no ocupa apenas nada y se actualiza sola.": "Queda co emblema do club na túa pantalla de inicio e ábrese a pantalla completa, coma calquera outra aplicación. É esta mesma páxina: apenas ocupa nada e actualízase soa.",
  "Instalar en este dispositivo": "Instalar neste dispositivo",
  "Toca el botón de compartir, el cuadrado con la flecha hacia arriba.": "Toca o botón de compartir, o cadrado coa frecha cara arriba.",
  "Baja y elige «Añadir a pantalla de inicio».": "Baixa e escolle «Engadir á pantalla de inicio».",
  "Confirma. Te queda el emblema del club junto a tus demás aplicaciones.": "Confirma. Quédache o emblema do club xunto ás demais aplicacións.",
  "Desde el menú de tu navegador, busca «Instalar aplicación» o «Añadir a pantalla de inicio».": "Desde o menú do teu navegador, busca «Instalar aplicación» ou «Engadir á pantalla de inicio».",
  "El Club Español del Perro Pastor Belga reúne a los criadores, deportistas y aficionados de las cuatro variedades del pastor belga.": "O Club Español do Can Pastor Belga reúne os criadores, deportistas e afeccionados das catro variedades do pastor belga.",
  "Hazte socio": "Faite socio",

  /* Los reglamentos */
  "Los reglamentos del club": "Os regulamentos do club",
  "Toda la reglamentación": "Toda a regulamentación",
  "Descargar": "Descargar",
  "Reglamento de Cría del CEPPB": "Regulamento de Cría do CEPPB",
  "Anexo A · Salud": "Anexo A · Saúde",
  "El texto completo: aptos de cría, figuras, edades, cruces intervariedades y baremos.": "O texto completo: aptos de cría, figuras, idades, cruzamentos entre variedades e baremos.",
  "Las pruebas exigidas y sus resultados válidos: caderas, codos, LVT, genética y ADN.": "As probas esixidas e os seus resultados válidos: cadeiras, cóbados, LVT, xenética e ADN.",
  "Lo que la plataforma aplica sobre cada ficha, en su texto original. Para leerlo o llevártelo.": "O que a plataforma aplica sobre cada ficha, no seu texto orixinal. Para lelo ou levalo contigo.",

  /* Cuando el correo no consta en el censo */
  "Tu correo no consta en el censo": "O teu correo non consta no censo",
  "Has entrado con": "Entraches con",
  "y ese correo no figura en la ficha de ningún socio del club. El Libro de Cría es de uso interno: hasta que tu cuenta esté atada a una ficha del censo no se abre.": "e ese correo non figura na ficha de ningún socio do club. O Libro de Cría é de uso interno: ata que a túa conta estea ligada a unha ficha do censo non se abre.",
  "Dos motivos suele haber:": "Adoita haber dous motivos:",
  "La secretaría tiene otro correo tuyo. Escríbele y lo cambia, o entra con aquél.": "A secretaría ten outro correo teu. Escríbelle e cámbiao, ou entra con aquel.",
  "Todavía no eres socio del club.": "Aínda non es socio do club.",
  "¿Cuál de estas fichas es la tuya?": "Cal destas fichas é a túa?",
  "En el censo hay varias fichas con tu mismo correo, que es lo normal en una familia. Elige la tuya: sólo se ata una vez, así que asegúrate.": "No censo hai varias fichas co teu mesmo correo, o normal nunha familia. Escolle a túa: só se liga unha vez, así que asegúrate.",
  "Si ninguna es la tuya, escribe a la secretaría del club.": "Se ningunha é a túa, escribe á secretaría do club.",

  /* Me gusta y mensajes */
  "Me gusta": "Gústame",
  "Dile al propietario que te gusta": "Dille ao propietario que che gusta",
  "Ya te gusta. Púlsalo otra vez para quitarlo": "Xa che gusta. Preme outra vez para quitalo",
  "Escribir a su propietario": "Escribir ao propietario",
  "Escribirle": "Escribirlle",
  "Mensajes": "Mensaxes",
  "Recibidos": "Recibidas",
  "Enviados": "Enviadas",
  "Sin leer": "Sen ler",
  "Sin asunto": "Sen asunto",
  "De": "De",
  "Para": "Para",
  "Responder": "Responder",
  "Marcar leído": "Marcar como lida",
  "No tienes mensajes": "Non tes mensaxes",
  "Cuando otro socio te escriba desde tu perfil o desde la ficha de uno de tus perros, aparecerá aquí.": "Cando outro socio che escriba desde o teu perfil ou desde a ficha dun dos teus cans, aparecerá aquí.",
  "No has escrito a nadie todavía": "Aínda non lle escribiches a ninguén",
  "Desde la ficha de un socio o de un ejemplar puedes escribir a su propietario.": "Desde a ficha dun socio ou dun exemplar podes escribir ao seu propietario.",
  "Los socios se escriben aquí dentro, sin darse el correo. Si quieres darle el tuyo a alguien, se lo dices tú en el mensaje.": "Os socios escríbense aquí dentro, sen darse o correo. Se queres darlle o teu a alguén, dislle na mensaxe.",
  "Nada con ese nombre": "Nada con ese nome",

  /* Títulos, niveles y hermanos */
  "Títulos y niveles": "Títulos e niveis",
  "sin validar": "sen validar",
  "No cuentan hasta que la junta los coteja": "Non contan ata que a xunta os coteja",
  "Distinciones en concurso": "Distincións en concurso",
  "Todavía no hay ninguno validado por la junta.": "Aínda non hai ningún validado pola xunta.",
  "Hermanos": "Irmáns",
  "Escribir a un socio": "Escribir a un socio",
  "socios del club aceptan mensajes": "socios do club aceptan mensaxes",
  "Que me escriban": "Que me escriban",
  "Otros socios pueden escribirte desde la plataforma. No ven tu correo ni ningún otro dato tuyo: sólo tu nombre, para poder dirigirse a ti.": "Outros socios poden escribirche desde a plataforma. Non ven o teu correo nin ningún outro dato teu: só o teu nome, para poder dirixirse a ti.",
  "Sí, que me escriban": "Si, que me escriban",
  "Prefiero que no": "Prefiro que non",
};
