/* ============================================================
   Columnas que cada tabla admite al escribir.

   GENERADO por herramientas/generar-columnas.mjs a partir de
   db/schema.sql. No editar a mano: se vuelve a generar.

   Las columnas que calcula Postgres solo (nombre_completo,
   activo, es_criador) no están aquí a propósito: mandarlas
   haría fallar el guardado.
   ============================================================ */
"use strict";

const COLUMNAS = {
  admins: [
    "email",
    "nota",
    "nivel",
    "creado"
  ],
  socios: [
    "id",
    "numero",
    "auth_user_id",
    "nombre",
    "apellidos",
    "email",
    "telefono",
    "telefono2",
    "poblacion",
    "provincia",
    "cp",
    "pais",
    "fecha_nacimiento",
    "profesion",
    "bio",
    "web",
    "facebook",
    "instagram",
    "workingdog_perfil",
    "cuota",
    "fecha_alta",
    "fecha_baja",
    "socio_honor",
    "rsce_socio",
    "rsce_numero",
    "rsce_desde",
    "afijo",
    "afijo_fecha",
    "grupo_trabajo",
    "disciplinas",
    "variedades",
    "roles",
    "perfil_publico",
    "priv",
    "avatar_url",
    "idioma",
    "notas",
    "creado"
  ],
  socios_privado: [
    "socio_id",
    "dni",
    "direccion",
    "iban"
  ],
  invitaciones: [
    "token",
    "socio_id",
    "estado",
    "enviada",
    "aceptada",
    "caduca"
  ],
  perros: [
    "id",
    "nombre",
    "afijo",
    "afijo_socio_id",
    "variedad",
    "sexo",
    "fecha_nacimiento",
    "fecha_fallecimiento",
    "color",
    "loe",
    "chip",
    "tatuaje",
    "propietario_id",
    "criador_id",
    "padre_id",
    "madre_id",
    "adn_ejemplar",
    "salud",
    "salud_validacion",
    "salud_validada_por",
    "salud_validada_fecha",
    "salud_validacion_nota",
    "visibilidad",
    "avatar_url",
    "workingdog_url",
    "pedigri_pegado",
    "historial_titularidad",
    "origen",
    "creado"
  ],
  eventos: [
    "id",
    "nombre",
    "tipo",
    "fecha",
    "cierre",
    "lugar",
    "juez",
    "organizado_ceppb",
    "directo_url",
    "directo_titulo",
    "creado"
  ],
  resultados: [
    "id",
    "perro_id",
    "tipo",
    "fecha",
    "evento",
    "evento_id",
    "tipo_evento",
    "juez",
    "organizado_ceppb",
    "calificacion",
    "clase",
    "puesto",
    "distincion",
    "modalidad",
    "resultado",
    "titulo",
    "puntos",
    "guia",
    "anio",
    "calificacion_origen",
    "puntos_sobre",
    "equipo",
    "validado",
    "validado_por",
    "validado_fecha",
    "validado_nota",
    "registrado_por",
    "creado"
  ],
  megusta: [
    "perro_id",
    "socio_id",
    "creado"
  ],
  mensajes: [
    "id",
    "de_id",
    "para_id",
    "perro_id",
    "asunto",
    "cuerpo",
    "leido",
    "creado"
  ],
  inscripciones: [
    "id",
    "evento_id",
    "perro_id",
    "socio_id",
    "clase",
    "estado",
    "fecha"
  ],
  camadas: [
    "id",
    "padre_id",
    "madre_id",
    "criador_id",
    "afijo",
    "fecha_nacimiento",
    "n_machos",
    "n_hembras",
    "loe_camada",
    "fecha_comunicacion",
    "recomendada",
    "intervariedad",
    "notas",
    "creado"
  ],
  solicitudes: [
    "id",
    "tipo",
    "estado",
    "fecha",
    "macho_id",
    "hembra_id",
    "criador_id",
    "linea",
    "motivo",
    "docs",
    "perro_id",
    "de_socio_id",
    "a_socio_id",
    "fecha_efecto",
    "documento",
    "resolucion",
    "fecha_resolucion",
    "resuelta_por",
    "solicitante_id",
    "creado"
  ],
  pagos: [
    "id",
    "socio_id",
    "anio",
    "concepto",
    "importe",
    "estado",
    "fecha"
  ],
  media: [
    "id",
    "tipo",
    "sujeto",
    "perro_id",
    "socio_id",
    "storage_path",
    "url",
    "proveedor",
    "titulo",
    "subido_por",
    "fecha",
    "validado",
    "duracion",
    "nota",
    "youtube_url"
  ]
};
